version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/src
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    command: bash -c "
      python3 /src/manage.py collectstatic --no-input &&
      python3 /src/manage.py makemigrations &&
      python3 /src/manage.py migrate &&
      gunicorn /src/config.wsgi:application -b 0:80"
    volumes:
      - .:/src
      - ./config/gunicorn:/etc/systemd/system